### ISSUE TITLE
gs.getUser().getID() and other functions not being passed properly?

### ISSUE THREAD

**Issue by kylecribbs** [thewhitespace/Xplore#33] opened 2020-07-23 05:39 UTC
I have wrote a script include class called UserObject where we are checking different attributes about the user.

When I pass the following code to Xplore I get `false` and we expect it to be `true`
```javascript
var project = "1ac9ec1f8dfd10107f61449ff67c8fb4";
var operation = "read";
var permissions_column = "ports_protocols_services";

var userObject = new x_snc_authorizatio.UserObject(gs.getUser().getID());
userObject.isUserAuthorized(project, operation, permissions_column).stakeholder();
```

When I pass the same code to Background Script i get `true`

When I hardcode `gs.getUser().getID()` I get `true`
```javascript
var project = "1ac9ec1f8dfd10107f61449ff67c8fb4";
var operation = "read";
var permissions_column = "ports_protocols_services";
var user_id = "3a98e903810d50107f612b41b4439bef";

var userObject = new x_snc_authorizatio.UserObject(user_id);
userObject.isUserAuthorized(project, operation, permissions_column).stakeholder();
```

Seems like gs.getUser() is getting passed weird to the server side, or it is getting passed to a script include weird.

**Comment by kylecribbs** [comment] 2020-07-23 05:44
Another weird part is this:
When I call 
```javascript
var project = "1ac9ec1f8dfd10107f61449ff67c8fb4";
var operation = "read";
var permissions_column = "ports_protocols_services";

var userObject = new x_snc_authorizatio.UserObject("3a98e903810d50107f612b41b4439bef");
userObject.userId
```
it ouputs 
```
Type | JavaObject
-- | --
"3a98e903810d50107f612b41b4439bef"
```

and it has exactly the same output for
```javascript
var project = "1ac9ec1f8dfd10107f61449ff67c8fb4";
var operation = "read";
var permissions_column = "ports_protocols_services";

var userObject = new x_snc_authorizatio.UserObject(gs.getUser().getID());
userObject.userId
```

**Comment by kylecribbs** [comment] 2020-07-23 05:48
I believe I may have found the issue. When running `gs.info(typeof(userObject.userId));` in the Background Script is shows it as a string. When I run the same thing in Xplore it comes back as an Object.

**Comment by jneale** [comment] 2020-11-25 15:08
Hi Kyle,

I've tested and Xplore appears to be fine.
Closing as not able to reproduce with the following similar test.

```javascript
function Auth(user_id) {
  this.user_id = user_id;
}

Auth.prototype.isOK = function () { 
  return !!this.user_id;
}

var obj = new Auth(gs.getUser().getID())
obj.isOK()
```

FYI, shorthand for `gs.getUser().getID()` is `gs.getUserID()`.

Thanks,
James

**Closed by jneale** 2020-11-25 15:08 UTC

**Comment by kylecribbs** [comment] 2020-11-25 16:13
It would be nice to have a discussion about this. It seems like everything from xplore returns as an object rather than it’d actual type. For example, if I don’t get getDisplayValue on a glide record field value it will return “{}”.

**Comment by jneale** [comment] 2020-11-25 17:12
What version of Xplore are you using? In 4.7 GlideElement objects are printed correctly with the values showing.

![image](https://user-images.githubusercontent.com/1355440/100260500-5f1c4500-2f41-11eb-9c02-a561ad0436a6.png)

**Comment by ahalstead-sctg** [comment] 2020-11-25 17:42
Hey Kyle, your beef is with the way dynamic weak typing (JavaScript) interfaces with static strong typing (Java) in SN's setup, not Xplore itself. You can't really expect JS to be consistent with metadata, there are no types, just primitives. If your code depends on something being a string vs some 'type', that is a code smell and you should fix it. In your example, field accessing should always be done through a function ie `getValue()` to ensure consistency
