### ISSUE TITLE
New Feature Request - Allow use of macros

### ISSUE THREAD

**Issue by kev1nme1er** [thewhitespace/Xplore#31] opened 2019-09-06 16:37 UTC
Others are asking for the ability to save/load code snippets, which would be fantastic.  This request is of a similar nature in that it would be great to have access to Syntax Editor Macros within Xplore.

Thanks.

**Comment by jneale** [comment] 2019-09-10 08:06
Noted. Closing as duplicate of #27

**Closed by jneale** 2019-09-10 08:06 UTC
